### ISSUE TITLE
Error while configuring AspNetIdentity with IdentityServer3: method does not exist.

### ISSUE THREAD

**Issue by adrianohck** [IdentityServer/Thinktecture.IdentityServer3.AspNetIdentity#31]
Hi, 

I'm trying to configure AspNetIdentity in my IdentityServer as following:

-------------------
    public class Factory
    {
        public static IdentityServerServiceFactory Configure(string connString)
        {
            //-- using identity server with entity framework
            var efConfig = new EntityFrameworkServiceOptions
            {
                ConnectionString = connString,
            };

            var factory = new IdentityServerServiceFactory();
            factory.RegisterOperationalServices(efConfig);

            //-- try to configure AspNetIdentityUserService....
            factory.ConfigureUserService("AspId");   // <-  here is the error: The method ConfigureUserService does not exist.

            return factory;
        }

    }
-------------------

But I'm getting an error message that says: 'Thinktecture.IdentityServer.Core.Configuration.IdentityServerServiceFactory' does not contain a definition for 'ConfigureUserService'.

I have already installed the package:
https://www.nuget.org/packages/Thinktecture.IdentityServer3.AspNetIdentity/

**Comment by brockallen** [comment]
That's an extension method from the hosting sample.

**Comment by adrianohck** [comment]
ohhh, allright. Now I found it. Thank you verry much!
